Repository ROCm/torch_migraphx, pull requests merged in 2024-09, with the labels that each got.

#181 tensor_mode support for div
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
  tests/dynamo/converters/test_pointwise_ops_dynamo.py
  tests/fx/converters/test_pointwise_ops_fx.py
Labels: TorchMIGraphX, Op Support

#190 torch.compile fix tensor_meta on nodes with multiple outputs
  py/torch_migraphx/dynamo/lower_dynamo.py
  py/torch_migraphx/dynamo/passes/fix_tensor_meta.py
Labels: bugfix

#197 build update
  ci/build.Dockerfile
  ci/build_whl.sh
  ci/excludes.params
  py/version.txt
Labels: noCI

#201 add torchbench dockerfile and workflow
  .github/workflows/torchbench.yaml
  docker/torchbench.Dockerfile
Labels: TorchMIGraphX

#168 bump migraphx release
  .github/workflows/ci.yaml
  Jenkinsfile
  ci/base.Dockerfile
Labels: TorchMIGraphX
