Repository ROCm/torch_migraphx, pull requests merged in 2024-11, with the labels that each got.

#176 153 op support atenrepeatdefault
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
  tests/dynamo/converters/test_shape_ops_dynamo.py
  tests/fx/converters/test_shape_ops_fx.py
Labels: TorchMIGraphX

#175 154 op support atengludefault
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
  tests/dynamo/converters/test_activations_dynamo.py
  tests/fx/converters/test_activations_fx.py
Labels: TorchMIGraphX

#214 fix googlenet test case for pyt2.5
  py/torch_migraphx/fx/tracer/acc_tracer/acc_tracer.py
  tests/fx/models/test_lowering_fx.py
Labels: bugfix

#215 move torch tensors to cpu as graph is interpreted
  py/torch_migraphx/dynamo/lower_dynamo.py
  py/torch_migraphx/fx/fx2mgx.py
Labels: enhancement

#216 Add aten efficient attn converter
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  tests/dynamo/converters/test_attn_dynamo.py
Labels: TorchMIGraphX
