Repository ROCm/torch_migraphx, pull requests merged in 2024-05, with the labels that each got.

#89 add check for tensor_meta when trying to promote intputs
  py/torch_migraphx/dynamo/passes/promote_types.py
Labels: bug, TorchMIGraphX

#90 Fix default strides for aten pooling ops
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  tests/dynamo/converters/test_pooling_dynamo.py
Labels: TorchMIGraphX

#106 add aten converter for neg
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  tests/dynamo/converters/test_pointwise_ops_dynamo.py
Labels: TorchMIGraphX, Op Support

#108 add support for isinf
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
  tests/dynamo/converters/test_bool_ops_dynamo.py
  tests/fx/converters/test_bool_ops_fx.py
Labels: TorchMIGraphX, Op Support

#109 add support for aten cumsum
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  tests/dynamo/converters/test_reduce_ops_dynamo.py
Labels: TorchMIGraphX, Op Support

#127 add converter for sqrt function
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  tests/dynamo/converters/test_pointwise_ops_dynamo.py
Labels: enhancement, good first issue, TorchMIGraphX, Op Support
