Repository ROCm/torch_migraphx, pull requests merged in 2024-08, with the labels that each got.

#172 propagate "bool_output" flag through shape ops
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  tests/fx/converters/test_shape_ops_fx.py
Labels: TorchMIGraphX, bugfix

#173 support zeros_like and add test cases for remove_ops pass
  py/torch_migraphx/dynamo/passes/remove_ops.py
  tests/conftest.py
  tests/dynamo/passes/dynamo_passes_test_utils.py
  tests/dynamo/passes/test_remove_const_ops.py
Labels: TorchMIGraphX

#174 add aten.fill converter
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  tests/dynamo/converters/test_bool_ops_dynamo.py
Labels: TorchMIGraphX, Op Support

#170 Bitwise and
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
  tests/dynamo/converters/test_pointwise_ops_dynamo.py
  tests/fx/converters/test_pointwise_ops_fx.py
Labels: Op Support

#169 157 op support atentopkdefault
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  tests/dynamo/converters/test_maxmin_dynamo.py
Labels: TorchMIGraphX, Op Support

#162 log2 added
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
  tests/dynamo/converters/test_pointwise_ops_dynamo.py
  tests/fx/converters/test_pointwise_ops_fx.py
  tests/fx/tracer/test_acc_tracer.py
Labels: TorchMIGraphX, Op Support

#180 aten_erf_setup
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
  tests/dynamo/converters/test_pointwise_ops_dynamo.py
  tests/fx/converters/test_pointwise_ops_fx.py
Labels: TorchMIGraphX, Op Support

#179 aten log support
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  tests/dynamo/converters/test_pointwise_ops_dynamo.py
Labels: TorchMIGraphX, Op Support
