Repository ROCm/torch_migraphx, pull requests merged in 2024-07, with the labels that each got.

#144 Reciprocal op converter, ATen. An acc_ops converter …
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  tests/dynamo/converters/test_pointwise_ops_dynamo.py
Labels: TorchMIGraphX, Op Support

#150 update pt2e call in tools for torch >= 2.2
  tools/perf/benchmark_quantized.py
Labels: TorchMIGraphX, bugfix

#158 add min migraphx version parameter to register_converter decorator
  py/torch_migraphx/fx/converter_registry.py
Labels: enhancement, TorchMIGraphX

#159 support scalar shaped tensor input to masked fill
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  tests/dynamo/converters/test_bool_ops_dynamo.py
  tests/fx/converters/test_bool_ops_fx.py
Labels: TorchMIGraphX, Op Support

#161 add fixtures required to skip tests based on migraphx version
  tests/conftest.py
Labels: TorchMIGraphX

#141 Nll loss converter
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
  tests/dynamo/converters/test_activations_dynamo.py
  tests/fx/converters/test_activations_fx.py
Labels: TorchMIGraphX, Op Support

#160 rsqrt added
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
  tests/dynamo/converters/test_pointwise_ops_dynamo.py
  tests/fx/converters/test_pointwise_ops_fx.py
Labels: TorchMIGraphX

#164 Added aten converter for the unary op "floor"
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  tests/dynamo/converters/test_pointwise_ops_dynamo.py
Labels: TorchMIGraphX, Op Support

#167 add converters for logical_not, for both aten and acc. Includes tests
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
  tests/dynamo/converters/test_pointwise_ops_dynamo.py
  tests/fx/converters/test_pointwise_ops_fx.py
Labels: TorchMIGraphX, Op Support

#142 aten.any.default and aten.all.default and fx converters
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
  tests/dynamo/converters/test_reduce_ops_dynamo.py
  tests/fx/converters/test_reduce_ops_fx.py
Labels: TorchMIGraphX, Op Support

#166 Support linalg_vector_norm
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
  tests/dynamo/converters/test_linalg_ops_dynamo.py
  tests/fx/converters/test_linalg_ops_fx.py
Labels: TorchMIGraphX, Op Support

#171 add requirements file to tools/perf scripts
  tools/perf/requirements.txt
Labels: noCI
