Repository ROCm/torch_migraphx, pull requests merged in 2024-06, with the labels that each got.

#128 Implement aten.minimum.default converter and move tests
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
  tests/dynamo/converters/test_bool_ops_dynamo.py
  tests/dynamo/converters/test_pointwise_ops_dynamo.py
  tests/fx/converters/test_bool_ops_fx.py
  tests/fx/converters/test_pointwise_ops_fx.py
Labels: Op Support

#132 add explicit conversion of min and max in clamp converter
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  tests/dynamo/converters/test_activations_dynamo.py
Labels: TorchMIGraphX, bugfix

#138 aten.lift ops
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  tests/dynamo/converters/test_shape_ops_dynamo.py
Labels: TorchMIGraphX, Op Support

#140 Add scatter reduce converters
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  py/torch_migraphx/fx/converters/utils.py
  py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
  tests/dynamo/converters/test_select_scatter_ops_dynamo.py
  tests/fx/converters/test_scatter_ops_fx.py
Labels: TorchMIGraphX, Op Support

#139 support torch.index_select
  py/torch_migraphx/fx/converters/acc_ops_converters.py
  py/torch_migraphx/fx/converters/aten_ops_converters.py
  py/torch_migraphx/fx/tracer/acc_tracer/acc_ops.py
  tests/dynamo/converters/test_select_scatter_ops_dynamo.py
  tests/fx/converters/test_getitem_fx.py
Labels: TorchMIGraphX, Op Support
